# Site settings
title:             Tech
sitename:          Jampp Geeks Blog
title-divider:     "|"
email:             tech@jammp.com
description:       Jampp Geeks - tech, python, big data, data science and random interesting stuff!
locale:            en_US
owner:             Patricio Rocca Huguet

twitter_username:  jampp
github_username:   jampp
facebook_username: jamppHQ
linkedin_username: jampp

google_analytics: UA-22947720-14

production:        false

baseurl:           ""
url:               ""

source:            ./_src
destination:       ./build

permalink:         /:categories/:title/

paginate:          7 # Only 6 post on front page. Plus the offset of first post
paginate_path:     '/page:num'
gems:              
 - jekyll-paginate
 - jekyll-sitemap

# Any entry from the IANA Time Zone Database
timezone:          America/Argentina/Buenos_Aires

# Build settings
markdown:          kramdown

# Gulp takes care of images and assets
exclude:           ['images', 'css', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'page-template.html']

# Don't import the folder structure
exclude:           []

# `_config.build.yml` sets `future` and `show_drafts` to `false`
future:            true
show_drafts:       true
